

-- CREANDO LAS TABLAS PRIMARIAS

CREATE TABLE TA_TIPO_ADJU
(
  ID_TIPO_ADJU CHAR(5) PRIMARY KEY,
  NO_TIPO_ADJU VARCHAR(20) NOT NULL,
  ES_TIPO_ADJU CHAR(1) NOT NULL
);

COMMENT ON TABLE  TA_TIPO_ADJU IS 'TABLA DE APOYO DE LOS TIPOS DE ADJUNTOS.';
COMMENT ON COLUMN TA_TIPO_ADJU.ID_TIPO_ADJU IS 'CODIGO DEL TIPO DE ADJUNTO.';
COMMENT ON COLUMN TA_TIPO_ADJU.NO_TIPO_ADJU IS 'NOMBRE DEL TIPO DE ADJUNTO.';
COMMENT ON COLUMN TA_TIPO_ADJU.ES_TIPO_ADJU IS 'ESTADO DEL TIPO DE ADJUNTO.';


CREATE TABLE TP_FLYER 
(
  ID_FLYER CHAR(5) PRIMARY KEY,
  NO_FLYER VARCHAR(20) NOT NULL,
  IG_FLYER BYTEA NOT NULL,
  DA_USER_FLYER VARCHAR(30) NOT NULL,
  DA_IP_USER_FLYER CHAR(15) NOT  NULL,
  DA_DESKTOP_USER_FLYER VARCHAR(25),
  FE_SUB_FLYER VARCHAR(30) DEFAULT TO_CHAR(NOW(),'DD/MM/YYYY HH24:MI:SS'),
  ES_FLYER CHAR(1) DEFAULT 'A'
);

COMMENT ON TABLE TP_FLYER IS 'TABLA PRINCIPAL DE LOS FLYERS.'
COMMENT ON COLUMN TP_FLYER.ID_FLYER IS 'CODIG DEL FLYER.';
COMMENT ON COLUMN TP_FLYER.NO_FLYER IS 'NOMBRE DEL FLYER.';
COMMENT ON COLUMN TP_FLYER.IG_FLYER IS 'IMAGEN DEL FLYER.';
COMMENT ON COLUMN TP_FLYER.DA_USER_FLYER IS 'USUARIO QUE REGISTRO EL FLYER.';
COMMENT ON COLUMN TP_FLYER.DA_IP_USER_FLYER IS 'IP DEL HOST DEL USUARIO QUE SUBIO EL FLYER.';
COMMENT ON COLUMN TP_FLYER.DA_DESKTOP_USER_FLYER IS 'NOMBRE DEL HOST DE DONDE SE SUBIO EL FLYER.';
COMMENT ON COLUMN TP_FLYER.FE_SUB_FLYER IS 'FECHA DE SUBIDA DEL FLYER.';
COMMENT ON COLUMN TP_FLYER.ES_FLYER IS 'ESTADO DEL FLYER.'


CREATE TABLE TP_POLI_SEGU
(
  ID_POLI_SEGU CHAR(5) PRIMARY KEY,
  NO_POLI_SEGU VARCHAR(50) NOT NULL,
  IG_POLI_SEGU BYTEA NOT NULL,
  DA_USER_POLI_SEGU VARCHAR(20) NOT NULL,
  DA_IP_USER_POLI_SEGU CHAR(15) NOT NULL,
  DA_DESKTOP_USER_POLI_SEGU VARCHAR(20) NOT NULL,
  FE_SUB_INFO VARCHAR(30) DEFAULT TO_CHAR(NOW(),'DD/MM/YYYY HH24:MI:SS'),
  ES_POLI_SEGU CHAR(1) DEFAULT 'A'
);
COMMENT ON TABLE TP_POLI_SEGU IS 'TABLA PRINCIPAL DE LA POLIZAS DE SEGUROS.';
COMMENT ON COLUMN TP_POLI_SEGU.ID_POLI_SEGU IS 'CODIGO DEL POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.NO_POLI_SEGU IS 'NOMBRE DE LA POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.IG_POLI_SEGU IS 'IMAGEN DE LA POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.DA_USER_POLI_SEGU IS 'USUARIO QUE REGISTRO LA POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.DA_IP_USER_POLI_SEGU IS 'IP DEL HOST QUE SUBIO LA POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.DA_DESKTOP_USER_POLI_SEGU  IS 'HOST DE DONDE SE SUBIO LA POLIZA DE SEGURO.';
COMMENT ON COLUMN TP_POLI_SEGU.FE_SUB_INFO IS 'FECHA QUE SE REGISTRO LA POLIZA DE SEGURO.'
COMMENT ON COLUMN TP_POLI_SEGU.ES_POLI_SEGU IS 'ESTADO DE LA POLIZA DE SEGURO.';

--- CREANDO TABLAS SECUNDARIAS

CREATE TABLE TA_TIPO_INFO
(
  ID_TIPO_INFO CHAR(5) PRIMARY KEY,
  NO_TIPO_INFO VARCHAR(25) NOT NULL,
  DA_USER_TIPO_INFO VARCHAR(25) NOT NULL,
  DA_IP_TIPO_INFO CHAR(15) NOT NULL NOT NULL,
  DA_DESKTOP_TIPO_INFO VARCHAR(20) NOT NULL,
  FE_SUB_TIPO_INFO VARCHAR(25) DEFAULT TO_CHAR(NOW(),'DD/MM/YYYY HH24:MI:SS'),
  ES_TIPO_INFO CHAR(1) DEFAULT 'A',
  ID_POLI_SEGU CHAR(5),
  CONSTRAINT FK_TIPO_INFO_POLI_SEGU FOREIGN KEY(ID_POLI_SEGU) 
  REFERENCES TP_POLI_SEGU(ID_POLI_SEGU)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

COMMENT ON TABLE TA_TIPO_INFO IS 'TABLA DE APOYO DE LOS TIPO DE INFORMES.';
COMMENT ON COLUMN TA_TIPO_INFO.ID_TIPO_INFO IS 'CODIGO DEL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.NO_TIPO_INFO IS 'NOMBRE DEL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.DA_USER_TIPO_INFO IS 'USUARIO QUE REGISTRO EL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.DA_IP_TIPO_INFO IS 'IP DEL HOST DE DONDE SE REGISTRO EL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.DA_DESKTOP_TIPO_INFO IS 'HOST DE DONDE SE REGISTRO EL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.FE_SUB_TIPO_INFO IS 'FECHA QUE SE REGISTRO EL TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.ES_TIPO_INFO IS 'ESTADO DE TIPO DE INFORME.';
COMMENT ON COLUMN TA_TIPO_INFO.ID_POLI_SEGU IS 'CODIGO DE LA POLIZA DE SEGURO.'


CREATE TABLE TP_INFO 
(
  ID_INFO CHAR(5) PRIMARY KEY,
  NO_INFO VARCHAR(30) NOT NULL,
  ID_TIPO_INFO CHAR(5) NOT NULL,
  DO_INFO BYTEA NOT NULL,
  DA_USER_INFO CHAR(20) NOT NULL,
  DA_IP_USER_INFO CHAR(15) NOT NULL,
  DA_DESKTOP_USER_INFO VARCHAR(20) NOT NULL,
  FE_SUB_INFO VARCHAR(15) DEFAULT TO_CHAR(NOW(),'DD/MM/YYYY HH24:MI:SS'),
  ES_INFO CHAR(1) DEFAULT 'A',
  ID_POLI_SEGU CHAR(5),
  CONSTRAINT FK_TP_INFO_TP_POLI_SEGU FOREIGN KEY (ID_POLI_SEGU)
  REFERENCES TP_POLI_SEGU(ID_POLI_SEGU)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
COMMENT ON TABLE TP_INFO IS 'TABLA PRINCIPAL PARA LOS INFORMES'
COMMENT ON COLUMN TP_INFO.ID_INFO IS 'CODIGO DEL INFORME.';
COMMENT ON COLUMN TP_INFO.NO_INFO IS 'NOMBRE DEL INFORME.';
COMMENT ON COLUMN TP_INFO.ID_TIPO_INFO IS 'CODIGO DEL TIPO DE INFORME.';
COMMENT ON COLUMN TP_INFO.DO_INFO IS 'DOCUMENTO DE INFORME';
COMMENT ON COLUMN TP_INFO.DA_USER_INFO IS 'USUARIO QUE REGISTRO EL INFORME.';
COMMENT ON COLUMN TP_INFO.DA_IP_USER_INFO IS 'IP DEL HOST DONDE SE REGISTRO INFORME.';
COMMENT ON COLUMN TP_INFO.DA_DESKTOP_USER_INFO IS 'HOST DONDE SE REGISTRO EL INFORME';
COMMENT ON COLUMN TP_INFO.FE_SUB_INFO IS 'FECHA QUE SE REGISTRO EL INFORME';

CREATE TABLE TP_ADJU
(
  ID_ADJU CHAR(5) PRIMARY KEY,
  NO_ADJU VARCHAR(20) NOT NULL,
  DO_ADJU BYTEA,
  URL_ADJU VARCHAR(400),
  DA_USER_ADJU VARCHAR(20) NOT NULL,
  DA_IP_USER_ADJU CHAR(15) NOT  NULL,
  DA_DESKTOP_USER_ADJU VARCHAR(20) NOT  NULL,
  FE_SUB_ADJU VARCHAR(25) DEFAULT TO_CHAR(NOW(),'DD/MM/YYYY HH24:MI:SS'),
  ES_ADJU CHAR(1) DEFAULT 'A',
  ID_TIPO_ADJU CHAR(5),
  ID_FLYER CHAR(5),
  CONSTRAINT FK_TIPO_ADJU_TIPO_ADJU FOREIGN KEY(ID_TIPO_ADJU)
  REFERENCES TA_TIPO_ADJU(ID_TIPO_ADJU),
  CONSTRAINT FK_TIPO_ADJU_TP_FLYER FOREIGN KEY(ID_FLYER)
  REFERENCES TP_FLYER(ID_FLYER)
);

COMMENT ON TABLE TP_ADJU IS 'TABLA DEL ADJUNTO';
COMMENT ON COLUMN TP_ADJU.ID_ADJU IS 'CODIGO DEL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.NO_ADJU IS 'NOMBRE DEL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.DO_ADJU IS 'DOCUMENTO DEL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.URL_ADJU IS 'URL DE GOOGLE DRIVE.';
COMMENT ON COLUMN TP_ADJU.DA_USER_ADJU IS 'USUARIO QUE REGISTRO EL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.DA_IP_USER_ADJU IS 'IP DEL HOST DONDE SE REGISTRO EL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.DA_DESKTOP_USER_ADJU IS 'HOST DONDE SE REGISTRO EL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.FE_SUB_ADJU IS 'FECHA QUE SE REGISTRO EL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.ES_ADJU IS 'ESTADO DEL ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.ID_TIPO_ADJU IS 'CODDIO DEL TIPO DE ADJUNTO.';
COMMENT ON COLUMN TP_ADJU.ID_FLYER IS 'CODIGO DEL FLYER';

---- INSERTAR REGISTRO TABLAS PRIMARIAS -----

INSERT INTO TA_TIPO_ADJU
VALUES
('00001','PDF','A'),
('00002','URL GOOGLE DRIVE','A'),
('00003','EXCEL','A'),
('00004','WORD','A');





