
-- ***************** TABLAS PRIMARIAS ****************
-- LISTAR TIPO DE ADJUNTO
CREATE OR REPLACE FUNCTION SF_LIST_TIPO_ADJU
RETURNS TABLE(CODIGO VARCHAR,NOMBRE VARCHAR) 
AS 
$$
BEGIN
   RETURN QUERY 
   SELECT 
   ID_TIPO_ADJU AS CODIGO,
   NO_TIPO_ADJU AS NOMBRE,
   ES_TIPO_ADJU AS ESTADO
   FROM
   TA_TIPO_ADJU
   WHERE
   ES_TIPO_ADJU = 'A' 
   ORDER BY 
   NO_TIPO_ADJU ASC;
END;
$$ LANGUAGE plpgsql;

SELECT * FROM SF_LIST_TIPO_ADJU();

-- LISTAR POLIZA Y/O SEGUROS
CREATE OR REPLACE FUNCTION SF_LIST_POLI_SEGU
RETURNS TABLE(CODIGO VARCHAR,NOMBRE VARCHAR,IMAGEN BYTEA)
AS 
$$
BEGIN
  RETURN QUERY
  SELECT 
  ID_POLI_SEGU AS CODIGO,
  NO_POLI_SEGU AS NOMBRE,
  IG_POLI_SEGU AS IMAGEN
  FROM
  TP_POLI_SEGU
  WHERE
  ES_POLI_SEGU = 'A'
  ORDER BY 
  FE_SUB_INFO DESC;
END;
$$ LANGUAGE plpgsql;

-- LISTAR FLYERS 
CREATE OR REPLACE FUNCTION SF_LIST_FLYER
RETURNS TABLE(CODIGO VARCHAR,NOMBRE VARCHAR,IMAGEN BYTEA)
AS
$$
BEGIN
    SELECT
    ID_FLYER AS CODIGO,
    NO_FLYER AS NOMBRE,
    IG_FLYER AS IMAGEN
    FROM 
    TP_FLYER
    WHERE
    ES_FLYER = 'A'
    ORDER BY 
    FE_SUB_FLYER DESC;
END;
$$ LANGUAGE plpgsql;

-- ***************** TABLAS SECUNDARIAS ****************

-- LISTAR INFORMES
CREATE OR REPLACE FUNCTION SF_LIST_INFO(PIV_COD_POLI_SEGU VARCHAR,PIV_COD_TIPO_INFO VARCHAR)
RETURNS TABLE(CODIGO VARCHAR,NOMBRE VARCHAR,DOCUMENTO BYTEA)
AS
$$
BEGIN
    RETURN QUERY
    SELECT
    ID_INFO AS CODIGO,
    NO_INFO AS NOMBRE,
    DO_INFO AS DOCUMENTO
    FROM 
    TP_INFO
    WHERE
    ID_POLI_SEGU = PIV_COD_POLI_SEGU AND
    ID_TIPO_INFO = PIV_COD_TIPO_INFO AND
    ES_INFO = 'A'
    ORDER BY 
    FE_SUB_INFO DESC;
END;
$$ LANGUAGE plpgsql;
-- LISTAR TIPOS DE INFORMES
CREATE OR REPLACE FUNCTION SF_LIST_TIPO_INFO(PIV_COD_POLI_SEGU VARCHAR)
RETURNS TABLE(CODIGO VARCHAR,NOMBRE VARCHAR)
AS
$$
BEGIN 
  RETURN QUERY 
  SELECT 
  ID_TIPO_INFO AS CODIGO,
  NO_TIPO_INFO AS NOMBRE
  FROM 
  TA_TIPO_INFO
  WHERE
  ID_POLI_SEGU = PIV_COD_POLI_SEGU AND
  ES_TIPO_INFO = 'A'
  ORDER BY 
  FE_SUB_TIPO_INFO DESC;
END;
$$ LANGUAGE plpgsql;

-- LISTAR ADJUNTOS 
CREATE OR REPLACE FUNCTION SF_LIST_ADJU(PIV_COD_FLYER VARCHAR,PIV_COD_TIPO_ADJU VARCHAR)
RETURNS TABLE(CODIGO,NOMBRE,DOCUMENTO,URL_DRIVE)
AS
$$
BEGIN
    RETURN QUERY
    SELECT 
    ID_ADJU AS CODIGO,
    NO_ADJU AS NOMBRE,
    DO_ADJU AS DOCUMENTO,
    URL_ADJU AS URL_DRIVE
    FROM 
    TP_ADJU
    WHERE
    ID_FLYER = PIV_COD_FLYER AND
    ID_TIPO_ADJU = PIV_COD_TIPO_ADJU AND
    ES_ADJU = 'A';
END;
$$ LANGUAGE plpgsql;


